### PR TITLE
[do not merge] add cores flag

### PR DESCRIPTION
**Pull request by j23414**
### Description of proposed changes

Update documentation since newer version of snakemake requires `--cores`, matches the zika repo

### CODE REVIEW

**Review by tsibley — COMMENTED** [review]
FWIW, this isn't required when using Nextstrain CLI 4.0.0 and newer (released in June).

**Comment by j23414** [comment]
I see, nextstrain-cli is auto adding `--cores=all`

* https://github.com/nextstrain/cli/blob/ddcdf9c0cc911204fc90db5b3ff66f52504fae10/nextstrain/cli/command/build.py#L130

**Comment by j23414** [comment]
In that case, @tsibley  is it okay to submit PRs to remove `--cores all` flags from `nextstrain build .` statements in our documentation for consistency? 

* https://github.com/search?q=org%3Anextstrain+%22nextstrain+build+.+cores%22&type=code

* [ ] nextstrain/zika/README.md
* [ ] nextstrain/ncov/docs/src/tutorial/example-data.rst
* [ ] nextstrain/ncov/docs/src/tutorial/custom-data.rst
* [ ] nextstrain/ncov/docs/src/tutorial/genomic-surveillance.rst

@joverlee521 mentioned a good point that some people may be using an earlier version of nextstrain-cli (which would require `--cores all`). Then @corneliusroemer  also brought up a good point that if they are using an earlier version of nextstrain that there will be an error msg telling them to add the `--cores all` flag back in. Ergo easy to debug for both.

**Comment by tsibley** [comment]
@j23414 Yep, I'm supportive of removing `--cores all` from our documented `nextstrain build` invocations.

**Pull request closed without merging**
